<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.1.1
 */

/**
 * Database `benselectronics`
 */

/* `benselectronics`.`bpmlinks` */
$bpmlinks = array(
  array('siebelcircuit' => '95000234','customername' => 'Base Titanium','projectmanager' => 'Mary Murungi','accountmanager' => 'Philip Wasike','physicaladdress' => 'Ukunda','bandwidth' => 'IFB 10','servicetype' => 'MPLS','medium' => 'Fiber Passive','cperson' => 'Jonathan Munguire','cdetails' => ' 254 78299002','status' => 'completed','datereceived' => '2021-08-13','datecompleted' => '2021-08-17','comments' => 'On hold'),
  array('siebelcircuit' => '95004926','customername' => 'Shreej Enterprise','projectmanager' => 'James Konya','accountmanager' => 'Vilenda Kiprop','physicaladdress' => 'Mariakana','bandwidth' => '50 Mbps','servicetype' => 'Internet','medium' => 'Fiber Active','cperson' => 'Hiren Andore','cdetails' => '0737560996','status' => 'completed','datereceived' => '2021-08-18','datecompleted' => '2021-08-25','comments' => 'Closed on BPM'),
  array('siebelcircuit' => '95060784','customername' => 'KCB Kilifi','projectmanager' => 'Mary Murungi','accountmanager' => 'Charles Mwangangi','physicaladdress' => 'Kilifi','bandwidth' => 'IFB 20','servicetype' => 'LTE','medium' => 'Fiber GPON','cperson' => 'Prince Mukasi','cdetails' => '0788299911','status' => 'completed','datereceived' => '2021-08-13','datecompleted' => '2021-08-20','comments' => 'Closed on BPM'),
  array('siebelcircuit' => '95063356','customername' => 'Jambo Steel','projectmanager' => 'Dancan Mangori','accountmanager' => 'Mwikali','physicaladdress' => 'Mariakani','bandwidth' => 'IFB 3','servicetype' => 'MPLS','medium' => 'Fiber GPON','cperson' => 'Musyoka','cdetails' => '7987477748','status' => 'completed','datereceived' => '2021-08-18','datecompleted' => '2021-08-27','comments' => 'Network Issues'),
  array('siebelcircuit' => '95067735','customername' => 'KCB Mariakana','projectmanager' => 'Dancan Mangori','accountmanager' => 'Mwikali','physicaladdress' => 'Mazeras','bandwidth' => 'IFB 3','servicetype' => 'MPLS','medium' => 'Fiber GPON','cperson' => 'Steve Kithi','cdetails' => '7987477748','status' => 'completed','datereceived' => '2021-08-11','datecompleted' => '2021-08-19','comments' => 'Network Issues'),
  array('siebelcircuit' => '95067774','customername' => 'Watu Credit','projectmanager' => 'Geofry Muchiri','accountmanager' => 'Hamisi Ndula','physicaladdress' => 'Malindi','bandwidth' => '100 Mbps','servicetype' => 'Microwave','medium' => 'Ceragon','cperson' => 'Prince Mukasi','cdetails' => '0788299911','status' => 'returned','datereceived' => '2021-08-12','datecompleted' => '2021-08-10','comments' => 'Not fiber Ready'),
  array('siebelcircuit' => '95067777','customername' => 'Jambo Steel','projectmanager' => 'Dancan Mangori','accountmanager' => 'Mwikali','physicaladdress' => 'Mariakani','bandwidth' => 'IFB 3','servicetype' => 'MPLS','medium' => 'Fiber GPON','cperson' => 'Steve Kithi','cdetails' => '7987477748','status' => 'completed','datereceived' => '2021-08-26','datecompleted' => '2021-08-21','comments' => 'Installation'),
  array('siebelcircuit' => '95067784','customername' => 'Jambo Steel','projectmanager' => 'Dancan Mangori','accountmanager' => 'Mwikali','physicaladdress' => 'Mariakani','bandwidth' => 'IFB 3','servicetype' => 'MPLS','medium' => 'Fiber GPON','cperson' => 'Steve Kithi','cdetails' => '0788299911','status' => 'completed','datereceived' => '2021-08-13','datecompleted' => '2021-08-20','comments' => 'Network Issues'),
  array('siebelcircuit' => '95067788','customername' => 'Kenya bureau of standards','projectmanager' => 'Dancan Mangori','accountmanager' => 'Mwikali','physicaladdress' => 'Lamu','bandwidth' => 'IFB 3','servicetype' => 'E1','medium' => 'Fiber GPON','cperson' => 'Saliah','cdetails' => '0788299911','status' => 'completed','datereceived' => '2021-08-19','datecompleted' => '2021-08-20','comments' => 'Network Issues'),
  array('siebelcircuit' => '95067884','customername' => 'NAGID ABUBAKAR','projectmanager' => 'Mary Wangoi','accountmanager' => 'Metrine Nicholas','physicaladdress' => 'MALINDI','bandwidth' => '10 Mbps','servicetype' => 'Internet','medium' => 'Fiber GPON','cperson' => 'Najid Abubakari','cdetails' => '0785643254','status' => 'wip','datereceived' => '2021-08-20','datecompleted' => '2021-08-27','comments' => 'Physical Installation'),
  array('siebelcircuit' => '95067886','customername' => 'East African Roadways','projectmanager' => 'James Konya','accountmanager' => 'Vallary Ubare','physicaladdress' => 'Mombasa Bonje','bandwidth' => '15 Mbps','servicetype' => 'Internet','medium' => 'Fiber Active','cperson' => 'East African Roadways','cdetails' => '0704555777','status' => 'wip','datereceived' => '2021-08-20','datecompleted' => '2021-08-26','comments' => 'Intergration'),
  array('siebelcircuit' => '95068955','customername' => 'Watu Credit','projectmanager' => 'Geofrey Muchiri','accountmanager' => 'Charles Mwangangi','physicaladdress' => 'Mazeras','bandwidth' => '10 Mbps','servicetype' => 'Internet','medium' => 'Fiber Active','cperson' => 'Amhed','cdetails' => '0788299911','status' => 'wip','datereceived' => '2021-08-13','datecompleted' => '2021-08-18','comments' => 'Intergration'),
  array('siebelcircuit' => '95069935','customername' => 'KCB Mariakana','projectmanager' => 'Ernest Katama','accountmanager' => 'Mwikali','physicaladdress' => 'Mariakani','bandwidth' => 'IFB 3','servicetype' => 'MPLS','medium' => 'Fiber GPON','cperson' => 'Steve Kithi','cdetails' => '7987477748','status' => 'returned','datereceived' => '2021-08-12','datecompleted' => '2021-08-19','comments' => 'Installation'),
  array('siebelcircuit' => '95069957','customername' => 'Yehu','projectmanager' => 'Mary Murungi','accountmanager' => 'Mwanahidi','physicaladdress' => 'Mariakana','bandwidth' => '10 Mbps','servicetype' => 'gpon','medium' => 'LTE','cperson' => 'Mwema','cdetails' => '078883993','status' => 'completed','datereceived' => '2021-08-06','datecompleted' => '2021-08-13','comments' => 'Installation'),
  array('siebelcircuit' => '95069978','customername' => 'Mephi Services','projectmanager' => 'Nancy Mwithukia','accountmanager' => 'Hassan Abdi','physicaladdress' => 'Lamu','bandwidth' => '5 Mbps','servicetype' => 'Ceragon','medium' => 'LTE','cperson' => 'Kathere Kausi','cdetails' => '0712795883','status' => 'completed','datereceived' => '2021-08-12','datecompleted' => '2021-08-14','comments' => 'Customer not ready'),
  array('siebelcircuit' => '95069981','customername' => 'Northen King Transporters','projectmanager' => 'Broose Otieno','accountmanager' => 'Vallary Ubare','physicaladdress' => 'Sourthen House Msa','bandwidth' => 'IFB 5','servicetype' => 'Internet','medium' => 'Fiber GPON','cperson' => 'Abdililahidir','cdetails' => '0729764770','status' => 'wip','datereceived' => '2021-08-20','datecompleted' => '2021-08-25','comments' => 'Closed on BPM'),
  array('siebelcircuit' => '95069982','customername' => 'LCL Logistics','projectmanager' => 'Broose Otieno','accountmanager' => 'Vilenda Kiprop','physicaladdress' => 'Appolo house Mombasa','bandwidth' => 'IFB 10','servicetype' => 'Internet','medium' => 'Fiber GPON','cperson' => 'Padma Vasaran','cdetails' => ' 254732581833','status' => 'wip','datereceived' => '2021-08-18','datecompleted' => '2021-08-25','comments' => 'On hold'),
  array('siebelcircuit' => '95073376','customername' => 'Immigration Ministry','projectmanager' => 'Eureka Kingoo','accountmanager' => 'Humphrey Njeru','physicaladdress' => 'Kilindini','bandwidth' => '2 Mbps ','servicetype' => 'MPLS','medium' => 'Fiber Active','cperson' => 'Isaih koril','cdetails' => '0721418200','status' => 'wip','datereceived' => '2021-08-17','datecompleted' => '2021-08-24','comments' => 'Physical Installation'),
  array('siebelcircuit' => '95073461','customername' => '748 AIR SERVICES (K) LTD','projectmanager' => 'Beth Mulure','accountmanager' => 'Karanja Susan','physicaladdress' => 'Moi International Airport','bandwidth' => 'IFB 10','servicetype' => 'Internet','medium' => 'Fiber Active','cperson' => 'Desmont Wagumba','cdetails' => ' 254728748007','status' => 'wip','datereceived' => '2021-08-26','datecompleted' => '2021-09-02','comments' => 'Physical Installation'),
  array('siebelcircuit' => '95073904','customername' => 'AMADEUS EA','projectmanager' => 'Beth Muleru','accountmanager' => 'Vallary Ubare','physicaladdress' => 'Mombasa, Meru Road','bandwidth' => 'IFB 5','servicetype' => 'Internet','medium' => 'Fiber GPON','cperson' => 'Francis Katiku','cdetails' => ' 254725224242','status' => 'wip','datereceived' => '2021-08-26','datecompleted' => '2021-09-02','comments' => 'Intergration'),
  array('siebelcircuit' => '110653066','customername' => 'MDZONGOLONI SECONDARY SCHOOL','projectmanager' => 'Broose Otieno','accountmanager' => 'MWANAIDI RAMADHAN','physicaladdress' => 'Mdzongoloni Sec School Kilifi','bandwidth' => 'IFB 5','servicetype' => 'Internet','medium' => 'LTE','cperson' => 'SPONSOR ','cdetails' => '745137201','status' => 'completed','datereceived' => '2021-08-04','datecompleted' => '2021-08-06','comments' => 'Closed on Mail'),
  array('siebelcircuit' => '110653450','customername' => 'REUVEN HAROUSH','projectmanager' => 'Mary Murungi','accountmanager' => 'Esther Mutisya','physicaladdress' => 'LAMU','bandwidth' => 'IFB 5','servicetype' => 'Internet','medium' => 'LTE','cperson' => 'N/A','cdetails' => 'N/A','status' => 'wip','datereceived' => '2021-08-23','datecompleted' => '2021-08-24','comments' => 'Physical Installation'),
  array('siebelcircuit' => '110653460','customername' => 'JACKLINE GATAVI OWALA','projectmanager' => 'Mary Murungi','accountmanager' => 'Esther Mutisya','physicaladdress' => 'Gasaro Road, Mtwapa','bandwidth' => 'IFB 3','servicetype' => 'MPLS','medium' => 'LTE','cperson' => 'Jackline Owala','cdetails' => '722909830','status' => 'wip','datereceived' => '2021-08-20','datecompleted' => '2021-08-23','comments' => 'Physical Installation'),
  array('siebelcircuit' => '110660535','customername' => 'Total Kenya - MIA ','projectmanager' => 'James Konya','accountmanager' => 'Esther Mutisya','physicaladdress' => 'Moi International Airport','bandwidth' => 'IFB 5','servicetype' => 'Internet','medium' => 'LTE','cperson' => 'Wesley Ongoti','cdetails' => '0722878016','status' => 'wip','datereceived' => '2021-08-20','datecompleted' => '2021-08-23','comments' => 'Intergration'),
  array('siebelcircuit' => '1105366483','customername' => 'Base Titanium - Likoni','projectmanager' => 'Beth Muleru','accountmanager' => 'Vilenda Kiprop','physicaladdress' => 'Taara Building','bandwidth' => 'IFB 5','servicetype' => 'Internet','medium' => 'LTE','cperson' => 'Dena Geofrey','cdetails' => '0766443566','status' => 'wip','datereceived' => '2021-08-26','datecompleted' => '2021-09-02','comments' => 'Physical Installation'),
  array('siebelcircuit' => '1107758847','customername' => 'Lucy Wangeci','projectmanager' => 'Rispa Barasa','accountmanager' => 'Vincent Nguli','physicaladdress' => 'Kilifi Bofa Road','bandwidth' => '10 Mbps','servicetype' => 'Internet','medium' => 'LTE','cperson' => 'Kituu Kimba','cdetails' => '07440035256','status' => 'wip','datereceived' => '2021-08-26','datecompleted' => '2021-08-27','comments' => 'Intergration')
);

/* `benselectronics`.`entrylog` */
$entrylog = array(
  array('workorder' => 'BES0002574','entry' => '2574','clientname' => 'AFRICA DREAM LTD','circuitid' => '95069998','projectmanager' => 'STEVEN NGOMBO','date' => '2021-09-06','contact' => '0705349932 Rama','servicetype' => 'Internet','technology' => 'Active Fiber','jobdescription' => 'New installation','execution' => 'Deployment','status' => 'Completed','ipaddress' => 'N/A','physicallocation' => 'Lamu','buildingname' => 'Lamu lappest','buildingid' => 'N/A','orderdeadline' => '2021-09-13'),
  array('workorder' => 'BES0002575','entry' => '2575','clientname' => 'AFRICA DREAM LTD','circuitid' => '95069999','projectmanager' => 'Steven Ngombo','date' => '2021-09-06','contact' => '705349932 Rama','servicetype' => 'Internet','technology' => 'Active Fiber','jobdescription' => 'New installation','execution' => 'Deployment','status' => 'Completed','ipaddress' => 'N/A','physicallocation' => 'Lamu','buildingname' => 'Lamu lappest','buildingid' => 'N/A','orderdeadline' => '2021-09-13'),
  array('workorder' => 'BES0002576','entry' => '2576','clientname' => 'KENYA AIRPORTS AUTHORITY MALINDI','circuitid' => '95072612','projectmanager' => 'Steven Ngombo','date' => '2021-09-06','contact' => '0721944067 Stephen','servicetype' => 'Internet','technology' => 'Passive Fiber','jobdescription' => 'New installation','execution' => 'Deployment','status' => 'WIP','ipaddress' => 'N/A','physicallocation' => 'Malindi','buildingname' => 'KCAA Malindi','buildingid' => 'N/A','orderdeadline' => '2021-09-13'),
  array('workorder' => 'BES0002577','entry' => '2577','clientname' => 'TRANSFALGER ENTERPRISES LTD','circuitid' => '95069992','projectmanager' => 'Steven Ngombo','date' => '2021-09-06','contact' => '716588492 Rodger','servicetype' => 'Internet','technology' => 'Passive Fiber','jobdescription' => 'Fiber installation','execution' => 'Deployment','status' => 'WIP','ipaddress' => 'N/A','physicallocation' => 'Mombasa','buildingname' => 'Galaxy suri','buildingid' => 'N/A','orderdeadline' => '2021-09-13'),
  array('workorder' => 'BES0002578','entry' => '2578','clientname' => 'KENYA AIRPORTS AUTHORITY MOMBASA BACKUP','circuitid' => '95072614','projectmanager' => 'Sammy Mutisya','date' => '2021-09-06','contact' => '721944067 Stephen','servicetype' => 'Internet','technology' => 'Ceragon','jobdescription' => 'Deployment new installation back up link','execution' => 'Deployment','status' => 'WIP','ipaddress' => 'N/A','physicallocation' => 'Mombasa','buildingname' => 'MIA Mombasa','buildingid' => 'N/A','orderdeadline' => '2021-10-06'),
  array('workorder' => 'BES0002579','entry' => '2579','clientname' => 'KENYA AIRPORTS AUTHORITY MOMBASA PRIMARY','circuitid' => '95072608','projectmanager' => 'Steven Ngombo','date' => '2021-09-06','contact' => '0721944067 Stephen','servicetype' => 'Internet','technology' => 'Active Fiber','jobdescription' => 'New installation - Primary Link','execution' => 'Deployment','status' => 'WIP','ipaddress' => 'N/A','physicallocation' => 'Mombasa, Changamwe','buildingname' => 'MIA Mombasa','buildingid' => 'N/A','orderdeadline' => '2021-10-06'),
  array('workorder' => 'BES0002580','entry' => '2580','clientname' => 'LUCY MKAJUMA CHEA','circuitid' => '95069995','projectmanager' => 'Steven Ngombo','date' => '2021-09-07','contact' => '0722681011 Lucy','servicetype' => 'Internet','technology' => 'Passive Fiber','jobdescription' => 'Fiber installation','execution' => 'Deployment','status' => 'WIP','ipaddress' => 'N/A','physicallocation' => 'kilifi','buildingname' => 'AL-Madina','buildingid' => 'KLF242971','orderdeadline' => '2021-09-14'),
  array('workorder' => 'BES0002581','entry' => '2581','clientname' => 'JANET JACKSON AND SUSAN ADVOCATES','circuitid' => '95070607','projectmanager' => 'Sammy Mutisya','date' => '2021-09-08','contact' => '0797894689 JJ','servicetype' => 'Internet','technology' => 'Passive Fiber','jobdescription' => 'Deployment - Internet installation','execution' => 'Deployment','status' => 'Completed','ipaddress' => 'N/A','physicallocation' => 'Mombasa Town','buildingname' => 'NSSF House','buildingid' => 'N/A','orderdeadline' => '2021-09-15'),
  array('workorder' => 'BES0002582','entry' => '2582','clientname' => 'FRENCH DREAM LTD','circuitid' => '95069994','projectmanager' => 'Steven Ngombo','date' => '2021-09-08','contact' => '0735736908 Dominique','servicetype' => 'Internet','technology' => 'Passive Fiber','jobdescription' => 'Deployment -New installation','execution' => 'Deployment','status' => 'WIP','ipaddress' => 'N/A','physicallocation' => 'Diani','buildingname' => 'N/A','buildingid' => 'N/A','orderdeadline' => '2021-09-15'),
  array('workorder' => 'BES0002583','entry' => '2583','clientname' => 'NCPB-Mombasa_Depot','circuitid' => '95018599','projectmanager' => 'Geofrey Dena','date' => '2021-09-10','contact' => '722524414','servicetype' => 'WAN/IP MPLS','technology' => 'Wimax','jobdescription' => 'Support - Migration','execution' => 'Support','status' => 'WIP','ipaddress' => '172.30.46.126','physicallocation' => 'Mombasa','buildingname' => 'NCPB Depot Shimanzi','buildingid' => 'N/A','orderdeadline' => '2021-09-17'),
  array('workorder' => 'BES0002584','entry' => '2584','clientname' => 'URBANO LOUNGE LTD','circuitid' => '793456068','projectmanager' => 'Steven Ngombo','date' => '2021-09-11','contact' => 'Geoffrey 722218429','servicetype' => 'Internet','technology' => 'LTE','jobdescription' => 'Support - Relocation','execution' => 'Support','status' => 'Completed','ipaddress' => 'Dynamic','physicallocation' => 'Mombasa','buildingname' => 'N/A','buildingid' => 'N/A','orderdeadline' => '2021-09-13'),
  array('workorder' => 'BES0002585','entry' => '2585','clientname' => 'KENYA AIRPORTS AUTHORITY-MALINDI BACKUP','circuitid' => '95072618','projectmanager' => 'Dena','date' => '2021-09-11','contact' => '0721944067 Stephen','servicetype' => 'Internet','technology' => 'Ceragon','jobdescription' => 'Support -  New installation','execution' => 'Support','status' => 'WIP','ipaddress' => 'N/A','physicallocation' => 'Malindi','buildingname' => 'KCAA Malindi','buildingid' => 'N/A','orderdeadline' => '2021-09-17'),
  array('workorder' => 'BES0002586','entry' => '2586','clientname' => 'HAPA KENYA','circuitid' => '95074002','projectmanager' => 'Mercy Nzilili','date' => '2021-09-11','contact' => '0721838459 Martin','servicetype' => 'Internet','technology' => 'Active Fiber','jobdescription' => 'Support - relocation','execution' => 'Support','status' => 'WIP','ipaddress' => 'N/A','physicallocation' => 'Mombasa, Kongowea','buildingname' => 'Hapa Kenya Kongowea','buildingid' => 'N/A','orderdeadline' => '2021-09-17'),
  array('workorder' => 'BES0002587','entry' => '2587','clientname' => 'SAFEPAK LTD','circuitid' => '95074004','projectmanager' => 'Steven Ngombo','date' => '2021-09-11','contact' => '0724390700 Catherine','servicetype' => 'Internet','technology' => 'Active Fiber','jobdescription' => 'deployment ','execution' => 'Deployment','status' => 'Returned','ipaddress' => 'N/A','physicallocation' => 'Vipingo','buildingname' => 'N/A','buildingid' => 'N/A','orderdeadline' => '2021-09-17'),
  array('workorder' => 'BES0002588','entry' => '2588','clientname' => 'ROBSON HARRIS AND CO','circuitid' => '95073573','projectmanager' => 'Geofrey Dena','date' => '2021-09-13','contact' => '724320135 Julie','servicetype' => 'Internet','technology' => 'Passive Fiber','jobdescription' => 'Support Jobs','execution' => 'Support','status' => 'Completed','ipaddress' => 'N/A','physicallocation' => 'Mombasa','buildingname' => 'Ralli House','buildingid' => 'N/A','orderdeadline' => '2021-09-20'),
  array('workorder' => 'BES0002589','entry' => '2589','clientname' => 'MOHAMED HASSAN','circuitid' => '95072963','projectmanager' => 'Sammy Mutisya','date' => '2021-09-14','contact' => '0729232380 Mohamed','servicetype' => 'Internet','technology' => 'Passive Fiber','jobdescription' => 'Installation of fiber passive','execution' => 'Deployment','status' => 'Returned','ipaddress' => 'N/A','physicallocation' => 'Mombasa','buildingname' => 'Post Bank HSE','buildingid' => 'MBS141073','orderdeadline' => '2021-09-21'),
  array('workorder' => 'BES0002590','entry' => '2590','clientname' => 'SOTE LOGISTICS','circuitid' => '95072957','projectmanager' => 'Stevens Ngombo','date' => '2021-09-14','contact' => '0795579079 Susan','servicetype' => 'Internet','technology' => 'Passive Fiber','jobdescription' => 'Deployment new installation','execution' => 'Deployment','status' => 'Completed','ipaddress' => 'N/A','physicallocation' => 'Mombasa','buildingname' => 'Jubilee Arcade','buildingid' => 'MBS142533','orderdeadline' => '2021-09-21'),
  array('workorder' => 'BES0002591','entry' => '2591','clientname' => 'FATUMA UMAZI MWARUWA','circuitid' => '95067881','projectmanager' => 'Steven Ngombo','date' => '2021-09-14','contact' => '0757785030 Fatuma','servicetype' => 'Internet','technology' => 'Active Fiber','jobdescription' => 'Deployment of fiber active installation','execution' => 'Deployment','status' => 'Completed','ipaddress' => 'N/A','physicallocation' => 'Mariakani','buildingname' => 'Comfort Hotel','buildingid' => 'N/A','orderdeadline' => '2021-09-21'),
  array('workorder' => 'BES0002592','entry' => '2592','clientname' => 'SIMON NDURU KAGIA','circuitid' => '95074005','projectmanager' => 'Geofrey Dena','date' => '2021-09-14','contact' => '0702639900 Simon','servicetype' => 'Internet','technology' => 'Active Fiber','jobdescription' => 'Support','execution' => 'Support','status' => 'Completed','ipaddress' => 'N/A','physicallocation' => 'Ukunda','buildingname' => 'Umbi Complex','buildingid' => 'N/A','orderdeadline' => '2021-09-21'),
  array('workorder' => 'BES0002593','entry' => '2593','clientname' => 'SAFARI DOCTORS LTD','circuitid' => '95075214','projectmanager' => 'Steven','date' => '2021-09-16','contact' => ' 254721779081','servicetype' => 'Internet','technology' => 'Active Fiber','jobdescription' => 'Installation of new fiber','execution' => 'Deployment','status' => 'Completed','ipaddress' => 'N/A','physicallocation' => 'Lamu','buildingname' => 'N/A','buildingid' => 'N/A','orderdeadline' => '2021-09-23'),
  array('workorder' => 'BES0002594','entry' => '2594','clientname' => 'SAFARICOM LIMITED, ELI ZAPHAN HOUSE','circuitid' => '95074015','projectmanager' => 'Steven Ngombo','date' => '2021-09-16','contact' => ' 254700732529','servicetype' => 'Internet','technology' => 'Passive Fiber','jobdescription' => 'Installation of new fiber to the business ','execution' => 'Deployment','status' => 'WIP','ipaddress' => 'N/A','physicallocation' => 'MALINDI','buildingname' => 'ELI ZAPHAN HOUSE','buildingid' => 'N/A','orderdeadline' => '2021-09-23'),
  array('workorder' => 'BES0002595','entry' => '2595','clientname' => 'MARY GORRETI OCHWADA','circuitid' => '95074012','projectmanager' => 'Steven Ngombo','date' => '2021-09-17','contact' => 'Mary  254722326615','servicetype' => 'Internet','technology' => 'Passive Fiber','jobdescription' => 'Deploy installation','execution' => 'Deployment','status' => 'WIP','ipaddress' => 'N/A','physicallocation' => 'MALINDI','buildingname' => 'MALINDI COMPLEX','buildingid' => 'MLN141660 ','orderdeadline' => '2021-09-24'),
  array('workorder' => 'BES0002596','entry' => '2596','clientname' => 'ACK PWANI CHRISTIAN SERVICES-HANNAH MWANCIFI','circuitid' => '95074016','projectmanager' => 'Sammy','date' => '2021-09-17','contact' => 'Willis Oguta','servicetype' => 'Internet','technology' => 'Passive Fiber','jobdescription' => 'Deploy new nstallation of fiber Passive','execution' => 'Deployment','status' => 'WIP','ipaddress' => 'N/A','physicallocation' => 'Mombasa','buildingname' => 'ACK PLAZA','buildingid' => 'MBS141117','orderdeadline' => '2021-09-24'),
  array('workorder' => 'BES0002597','entry' => '2597','clientname' => 'DANCO HARDWARE AND ELECTRICALS','circuitid' => '95074013','projectmanager' => 'Sammy Mutisya','date' => '2021-09-18','contact' => ' 254718669192 Danco Hardware','servicetype' => 'Internet','technology' => 'Passive Fiber','jobdescription' => 'Installation of passive fiber','execution' => 'Deployment','status' => 'Returned','ipaddress' => 'N/A','physicallocation' => 'Ukunda','buildingname' => 'SIKU NJEMA PLAZA','buildingid' => 'N/A','orderdeadline' => '2021-09-25'),
  array('workorder' => 'BES0002598','entry' => '2598','clientname' => 'ASP  COMPANY LIMITED-2','circuitid' => '110653735','projectmanager' => 'Stevens','date' => '2021-09-22','contact' => 'Sai Srinivas 718848479           ','servicetype' => 'Internet','technology' => 'LTE','jobdescription' => 'LTE New Installation','execution' => 'Deployment','status' => 'Returned','ipaddress' => 'N/A','physicallocation' => 'KAJIADO COUNTY, ISINYA','buildingname' => 'N/A','buildingid' => 'N/A','orderdeadline' => '2021-09-23')
);

/* `benselectronics`.`instructions` */
$instructions = array(
  array('id' => '31','date' => '2021-09-11','mhr' => '0.3','pax' => '6','artisan' => 'Technician','instruction' => 'install fiber Gpon','rate' => '2.5','amount' => '4500','orderid' => 'BES0002580'),
  array('id' => '32','date' => '2021-09-13','mhr' => '2.8','pax' => '400','artisan' => 'Alex Muthui','instruction' => 'Installation fiber passive','rate' => '2','amount' => '5500','orderid' => 'BES0002588'),
  array('id' => '36','date' => '2021-09-07','mhr' => '0.5','pax' => '4','artisan' => 'Sammy','instruction' => 'Installation','rate' => '45','amount' => '9500','orderid' => 'BES0002588')
);

/* `benselectronics`.`orderitems` */
$orderitems = array(
  array('id' => '5','stockcode' => 'Flex','quantity' => '1','um' => 'meters ','description' => 'Connecting flex','up' => '150','value' => '200','orderid' => '95073904'),
  array('id' => '6','stockcode' => 'Trunk','quantity' => '1','um' => 'pcs','description' => 'trunking','up' => '150','value' => '150','orderid' => '95063804'),
  array('id' => '7','stockcode' => 'CabT','quantity' => '30','um' => 'pcs','description' => 'cable ties','up' => '20','value' => '600','orderid' => '95068704'),
  array('id' => '12','stockcode' => 'tr45','quantity' => '4','um' => 'meters ','description' => 'Trunking ','up' => '10','value' => '40','orderid' => 'BES0002576')
);

/* `benselectronics`.`session` */
$session = array(
  array('id' => '65','year' => '2020','session' => '')
);

/* `benselectronics`.`staff` */
$staff = array(
  array('id' => '7','firstname' => 'Mike','lastname' => 'Wanaswa','id_no' => '240678390','email' => 'mike@yahoo.com','username' => 'Munaa','mobileno' => '075432678'),
  array('id' => '8','firstname' => 'sammy','lastname' => 'Nzuki','id_no' => '35627881','email' => 'mwangi@yahoo.com','username' => 'samtish2010@gmail.com','mobileno' => '+2547233334')
);

/* `benselectronics`.`surveyjobs` */
$surveyjobs = array(
  array('customername' => 'ACK BISHOP HANNINGTON INSTITUT','solutionarchitect' => 'Rose Kimani','physicaladdress' => 'Mombasa - Buxton','coordinates' => '4 2 41.26 S 39 40 13.34 E','surveytype' => 'Microwave','reqcode' => 'REQ000003579810','contactperson' => 'Alfred Onyango','contactdetails' => '712479833','fieldengineer' => 'Benson Mangenyi','engcontacts' => '726732491','datereceived' => '2021-09-20','comments' => 'Building NOT Fiber ready, Manhole 300mtrs away. There\'s LOS, NO Ceragon covarage,LTE signal is good'),
  array('customername' => 'Amadeus Mada','solutionarchitect' => 'Daniel Kinuthia','physicaladdress' => 'Diani Ukunda','coordinates' => '4 56 56.67 S 39 34 34.54','surveytype' => 'Microwave','reqcode' => 'REQ00000435443','contactperson' => 'Kinyua','contactdetails' => '0','fieldengineer' => 'Benson','engcontacts' => '3547729902','datereceived' => '2021-08-19','comments' => 'Building is Fiber ready, LTE Coverage'),
  array('customername' => 'BOC Kenya LTD','solutionarchitect' => 'Daniel Kinuthia','physicaladdress' => 'Liwatoni - Mombasa','coordinates' => '4 03 56.2 S 39 39 35.3 E','surveytype' => 'All Media','reqcode' => 'REQ00000354834','contactperson' => 'Peter Muraya','contactdetails' => '725824649','fieldengineer' => 'Danson/Nyiro','engcontacts' => '702514903','datereceived' => '2021-08-25','comments' => 'Building is Not Fiber ready, LTE is Posible'),
  array('customername' => 'Cook N Lite','solutionarchitect' => 'Rose Kimani','physicaladdress' => 'Jela Baridi','coordinates' => '4 2 46.31 S 39 39 17.70 E','surveytype' => 'All Media','reqcode' => 'N/A','contactperson' => 'Cleopas Juma','contactdetails' => '737578050','fieldengineer' => 'Benson Mangenyi','engcontacts' => '726732491','datereceived' => '2021-09-20','comments' => 'Building Not fiber ready, Manhole 300Mtrs,LOS at Rooftop,Lte Signal good, No Ceragon Coverage'),
  array('customername' => 'Faulu Bank','solutionarchitect' => 'Rose Kimani','physicaladdress' => 'Mazeras','coordinates' => '4 56 56.67 S 39 34 34.56 E','surveytype' => 'WiFi','reqcode' => 'REQ00000433454','contactperson' => 'Muthuka','contactdetails' => '786533124','fieldengineer' => 'Benson','engcontacts' => '3547729902','datereceived' => '2021-08-26','comments' => 'Building is Fiber ready'),
  array('customername' => 'Faulu Branch - Mombasa','solutionarchitect' => 'Samuel Mwangi','physicaladdress' => 'Mombasa Town','coordinates' => '-4.6999 S 39.7778','surveytype' => 'WiFi','reqcode' => 'REQ0000043556','contactperson' => 'Amhed','contactdetails' => '734256678','fieldengineer' => 'Nyiro','engcontacts' => '724567621','datereceived' => '2021-08-26','comments' => 'Microwave, LTE, Ceragon Coverage'),
  array('customername' => 'Jambo Steel','solutionarchitect' => 'Daniel Kinuthia','physicaladdress' => 'Malindi','coordinates' => 'N/A','surveytype' => 'WiFi','reqcode' => 'REQ0000043556','contactperson' => 'Muthuka','contactdetails' => '7987477748','fieldengineer' => 'Ezekiel','engcontacts' => '724516789','datereceived' => '2021-08-11','comments' => 'Building is Fiber ready'),
  array('customername' => 'Kyosk Digital Services','solutionarchitect' => 'Kelvin Kuria','physicaladdress' => 'Millie Fruits Processors','coordinates' => '3 56 37.5 S 39 44 44 E','surveytype' => '','reqcode' => 'REQ000003578042','contactperson' => 'Paul Yamoh','contactdetails' => '110941308','fieldengineer' => 'Ron/Mercy','engcontacts' => '708040163','datereceived' => '2021-09-20','comments' => 'Not fiber Ready, JTL and Access Available, LTE'),
  array('customername' => 'Safarilympics(sportday/Events)','solutionarchitect' => 'Rose Kimani','physicaladdress' => 'Mombasa Sports Club','coordinates' => '4 3 49.03 S 39 40 3.33 E','surveytype' => 'All Media','reqcode' => 'REQ000003539257','contactperson' => 'Roe Kimani','contactdetails' => '718732253','fieldengineer' => 'Nicholas Nyundo','engcontacts' => '728997284','datereceived' => '2021-08-24','comments' => 'LTE Coverage,Microwave - Clear LOS to Mbarari BTS'),
  array('customername' => 'Watu Credit','solutionarchitect' => 'Abraham Agol','physicaladdress' => 'Kilifi','coordinates' => '4 56 56.67 S 39 34 34.56 E','surveytype' => '','reqcode' => 'REQ00000435443','contactperson' => 'Muthuka','contactdetails' => '786533124','fieldengineer' => 'Ezekiel','engcontacts' => '3547729902','datereceived' => '2021-08-17','comments' => 'Not fiber Ready')
);

/* `benselectronics`.`user` */
$user = array(
  array('id' => '18','username' => 'admin','password' => 'admin','salt' => '21232f297a57a5a743894a0e4a801fc3')
);
